##-----------PERMISSIONS
permissions:
  admin: "avpn.admin"
  bypass: "avpn.bypass"

##-----------MESSAGES
messages:
  country: "Your country is not allowed"
  vpn: "VPN is not allowed"
  max-connections: "Max connections per ip"
  ip-list: "Your ip is on blacklist"

##-----------COUNTRY CHECK
#If false whitelist is a blacklist
country:
  enabled: false
  only-attack: true
  whitelist: true
  list:
 #- DE

##-----------ASN CHECK
#EXPERIMENTAL check player organization asn
asn:
  enabled: true
  only-attack: true


#Maximum players connected with the same ip
max-join-per-ip:
  enabled: false
  limit: 4

#IP blacklist
ip-list:
  enabled: true
  only-attack: true


##-----------API CHECK
api:
  enabled: true


##-----------NICK CHECK
block_nick:
  enabled: true
  list:
    - "mcstorm"
    - "mcspam"
    - "mcdrop"
    - "bot"
    - "spam"
    - "spammer"

detect_attack:
  min-jps: 5

integrations:
  authme:
    enabled: false  #When attack is detected no registered players are not allowed to join.
    kick: "Saerver is attacked, wait a few minutes and connect again"
  discord:
    enabled: false
    webhook-url: ''


Debug: false
stats:
  blocked: 0

